language: python
python:
  - 2.7
# command to install dependencies
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy pytest 
  - conda install --yes python=$TRAVIS_PYTHON_VERSION matplotlib nose dateutil 
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pandas statsmodels pytables xlrd

#  - python setup.py install
#  - pip install -r preamble.txt
#  - pip install -r requirements.txt
#  - pip install -r denouement.txt

# command to run tests
script: 
  - ./run_tests

# the body of this script was found by @dan-blanchard at https://gist.github.com/dan-blanchard/7045057
